#!/bin/bash

#FONTS
sudo apt-get --ignore-missing install  -y unity-tweak-tool;
&&
sudo apt-get --ignore-missing install xfonts-terminus console-terminus ttf-droid ttf-dejavu ttf-liberation;
&&
fc-cache -f -v;
